services:
  debian-lab:
    build: .
    container_name: proyecto_admon_cliente
    networks:
      redProyecto:
        ipv4_address: 172.20.0.2
    volumes:
      - .:/workspace
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tty: true
    stdin_open: true
    restart: always
    privileged: true

  debian-lab2:
    build: .
    container_name: proyecto_admon_servidor
    networks:
      redProyecto:
        ipv4_address: 172.20.0.5
    tty: true
    stdin_open: true
    restart: always
    privileged: true

  debian-lab3:
    build: .
    container_name: proyecto_admon_servidor1
    networks:
      redProyecto:
        ipv4_address: 172.20.0.6
    tty: true
    stdin_open: true
    restart: always
    privileged: true    

  debian-lab4:
    build: .
    container_name: proyecto_admon_servidor2
    networks:
      redProyecto:
        ipv4_address: 172.20.0.7
    tty: true
    stdin_open: true
    restart: always
    privileged: true

networks:
  redProyecto:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16